# Generated by Django 4.1.1 on 2023-04-04 11:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Regalia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=256, verbose_name='ФИО')),
                ('first_name', models.CharField(max_length=256, null=True, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=256, null=True, verbose_name='Фамилия')),
                ('third_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Отчество')),
                ('en_regalia', models.CharField(blank=True, max_length=256, null=True, verbose_name='EN Регалия')),
                ('rank', models.CharField(blank=True, max_length=512, verbose_name='Должности, звания')),
                ('city', models.CharField(max_length=128, verbose_name='Город')),
                ('regalia', models.CharField(blank=True, max_length=512, verbose_name='Регалия')),
                ('comments', models.TextField(blank=True, verbose_name='Комментарии')),
                ('is_generated', models.BooleanField(default=False)),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='regalii_app.operation')),
            ],
        ),
    ]
